const level1 = new Level(
    [
        new Chicken(),
        new Chicken(),
        new Chicken(),
        new Endboss()
    ],
    [
        new Cloud(),
        new Cloud(),
        new Cloud(),
        new Cloud(),
    ],
    [
        new BackgroundObject('img/5_background/layers/air.png', -699),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', -699),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', -699),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', -699),
        new BackgroundObject('img/5_background/layers/air.png', 0),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 0),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 0),
        new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 0),
        new BackgroundObject('img/5_background/layers/air.png', 699),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 699),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 699),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 699),
        new BackgroundObject('img/5_background/layers/air.png', 1398),
        new BackgroundObject('img/5_background/layers/3_third_layer/1.png', 1398),
        new BackgroundObject('img/5_background/layers/2_second_layer/1.png', 1398),
        new BackgroundObject('img/5_background/layers/1_first_layer/1.png', 1398),
        new BackgroundObject('img/5_background/layers/air.png', 2097),
        new BackgroundObject('img/5_background/layers/3_third_layer/2.png', 2097),
        new BackgroundObject('img/5_background/layers/2_second_layer/2.png', 2097),
        new BackgroundObject('img/5_background/layers/1_first_layer/2.png', 2097),
    ],
    [
        new CollectableBottle(),
        new CollectableBottle(),
        new CollectableBottle(),
        new CollectableBottle(),
        new CollectableBottle(),
        new CollectableBottle(),
        new CollectableBottle(),
        new CollectableBottle(),
    ]
);